### ISSUE TITLE
Optional argument for expected label distribution

### ISSUE THREAD

**Issue by Garrafao** [pln-fing-udelar/fast-krippendorff#18]
the expected label distribution is currently inferred from the provided data. In some cases (e.g. with small data sets) it may be helpful to specify the expected label distribution inferred on (larger) external data. Does it make sense to add such an optional argument? If yes, I could create a pull request.

**Comment by bryant1410** [comment]
Hey. What you say is interesting. I have run into this as well, and I agree that in many cases it doesn't make sense. It's an issue (or supposition) from Krippendorff's Alpha. Similarly with Kappa.

Even though I understand your point and it's something that sounds principled to me (to be able to change the probability model and the way to do it), is this something that people have done or studied (i.e., do you have pointers?)? Because I think it goes a bit beyond the current scope, which is to support a fast Krippendorff's Alpha implementation, including its variations (e.g., different distance functions). I prefer for now to stick to common practices. But of course, feel free to fork this code and do it for your use case.

Another reason is that the API is simple right now, and unless this is a common use case, I prefer sticking to the main usages of it.

**Comment by Garrafao** [comment]
I do not have pointers for this, but have made my own experiments and also implemented it (it's just a minor adaption of your code). I don't know how useful it would be for people, so I guess it makes sense to keep your implementation simple, as long as there is no clear need for this feature.

**Comment by bryant1410** [comment]
Okay! I'm gonna close this. Feel free to continue the discussion if you want.

Not sure what you do, but maybe you find it interesting to study/research around it? Maybe something already exists, or maybe something can be created.

**Comment by Garrafao** [comment]
I'm using my adjusted variant of Krippendorf to compute agreement on word sense annotation ( https://aclanthology.org/N18-2027/ ). There we often have the situation where sentences of multiple different words are annotated on a scale from 1 to 4 (1 for unrelated, 4 for identical), but we want to know the agreement only on a subset of the data for a particular word. Often the label distribution is very skewed towards an annotation of 4 for words which have only one meaning, just as in the example I gave above. Then, currently, I estimate the expected label distribution not from the subset of data, but from the full annotated data. I think this can be motivated well from assumptions on random annotators as explained here: 

https://direct.mit.edu/coli/article/34/4/555/1999/Inter-Coder-Agreement-for-Computational

I did not stumble upon previous research on a similar modification of Krippendorf so far. If anyone finds something, please post it here. :-)
